### ISSUE TITLE
Omitting a font color throws NRE in Color parsing

### ISSUE THREAD

**Issue by peter-r-g** [Facepunch/sbox-iconify#2]
If you do not set a font color it will throw an NRE because null is being passed to the string > Color converter.
![image](https://github.com/Facepunch/sbox-iconify/assets/11802285/cc06b613-5caa-42d6-980f-eee6219d6a34)

**Comment by xezno** [comment]
Should be fixed with 7168f81d65e4149002249ee0b5c7930a7eeb0d70
